### ISSUE TITLE
#2 weekly news

### ISSUE THREAD

**Issue by garbas** [NixOS/nixos-weekly#14]
``#2 weekly release`` will happen on **Feb 06 2017**. 

## TODO 

- [ ] what would be the title (any suggestions?)
- [ ] select description/quote (any suggestions?)
- [ ] send first newsletter via mailchimp
- [ ] github issues statistics section (a script which would output new/closed issues/pr)
- [ ] move over, from ``#1`` edition, events that have not passed (berlin/amsterdam meetup)
- [ ] are there any blog posts that happen since 2 weeks
- [ ] are there any presentations (videos) that happen last 2 weeks
- [ ] what bigger PRs got merged in last 2 weeks
- [ ] is there any open discussion still happening and needs the input from the community
- [ ] in next edition we should mention the security team (get the intro paragraph from @grahamc )
- [ ] maybe @globin (release manager) would like to reveal his plan (timeline) for 17.03 and call others to help him
- [ ] it would be nice to document how the "release" process works since ``.travis.yml`` is not really that straight forward
- [ ] document in README how to write locally, ``nix-shell default.nix --run "python run.py``
- [ ] compile blog on each PR 
- [ ] use nixpkgs-python binary cache
- [ ] automate announcements on [nixos_org](https://twitter.com/nixos_org)
- [ ] add google analytics code

Please write suggestions in comments.

**Comment by grahamc** [comment]
Nixpkgs Overlays merged: https://github.com/NixOS/nixpkgs/pull/21243

**Comment by grahamc** [comment]
This article got a lot of attention: https://sourcediver.org/blog/2017/01/18/distributing-nixos-with-ipfs-part-1/

**Comment by garbas** [comment]
NYLUG Presents: Charles Strahan -on- Introduction to NixOS : https://www.youtube.com/watch?v=VivXSoovUFI

**Comment by globin** [comment]
I'm planning to announce the timeline today or tomorrow.

**Comment by garbas** [comment]
Erlang Factory SF 2016 - Erlang On NixOS Managing And Releasing Erlang Systems In The ...
Erlang Solutions: https://www.youtube.com/watch?v=xRSFJH3Lw6I

**Comment by badmutex** [comment]
Regarding Overlays: the mailing list post may also be a good resource to include:
https://www.mail-archive.com/nix-dev@lists.science.uu.nl/msg29484.html

**Comment by garbas** [comment]
Nix and Beyond: Pure Functional Package Management: https://www.meetup.com/Louisville-Haskell-Meetup/events/236727522/

**Comment by garbas** [comment]
Branch-Off and Release Timeline for #nixos 17.03: http://lists.science.uu.nl/pipermail/nix-dev/2017-January/022584.html

**Comment by garbas** [comment]
Stack + Nix = portable reproducible builds : http://blog.tweag.io/posts/2015-12-09-stack-nix.html

**Comment by teh** [comment]
garbas gave a talk (need skills matter account to view):

https://skillsmatter.com/skillscasts/9473-london-nixos-january-meetup

**Comment by garbas** [comment]
Hydra Building PRs

http://lists.science.uu.nl/pipermail/nix-dev/2017-January/022621.html

**Comment by garbas** [comment]
Typed Nix programming using Dhall 

http://www.haskellforall.com/2017/01/typed-nix-programming-using-dhall.html

**Comment by taktoa** [comment]
For any university students in the US, the University of Illinois at Urbana-Champaign is holding a hackathon oriented towards getting people into open source development, and I'm going to be mentoring people for Nix/NixOS/Haskell development. Be sure to put "NixOS" or "Haskell" into your application somewhere.

More info:
* https://hackillinois.org
* https://medium.com/@HackIllinois/open-source-2017-b322ad688471

**Comment by garbas** [comment]
https://twitter.com/thisissavo/status/826232064118755329

How i managed to get jekyll to work well on Nixos
https://thisissavo.github.io/programming/2017/01/30/jekyll-setup-in-nixos.html … #jekyll #NixOS #Linux #blogging #programming #noob #beginner

**Comment by garbas** [comment]
https://twitter.com/shajra/status/826249518161203205

Using Nix and Haskell together? I'd love feedback: https://github.com/shajra/example-nix

**Comment by teh** [comment]
A rust nightly nix thing: https://github.com/solson/rust-nightly-nix

**Comment by grahamc** [comment]
Update on hydra for PRs: http://lists.science.uu.nl/pipermail/nix-dev/2017-January/022643.html

The service is merging with hydra.nixos.org.

**Comment by garbas** [comment]
invite to contributors to triage github issues https://www.codetriage.com/nixos/nixpkgs

**Comment by rasendubi** [comment]
nix-bundle: Bundle Nix derivations to run anywhere: http://lists.science.uu.nl/pipermail/nix-dev/2017-February/022699.html

**Comment by grahamc** [comment]
@rasendubi that should probably go on this one: https://github.com/NixOS/nixos-weekly/issues/15 👍

**Comment by garbas** [comment]
oh yeah, i forgot to close this one
